#############################################################################
# Makefile for building: fsme
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  fsme.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile fsme.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUSE_SHARED_PTR -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = fsme1.0.0
DISTDIR = /an/fsme-code/.tmp/fsme1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		qdombasic.cpp \
		statemachine.cpp \
		streamable.cpp \
		eiobase.cpp \
		event.cpp \
		input.cpp \
		output.cpp \
		root.cpp \
		state.cpp \
		transition.cpp \
		diagramview.cpp \
		diagramscene.cpp \
		diagramstateitem.cpp \
		gsavers.cpp \
		diagramtransitionitem.cpp \
		chaikinarrow.cpp \
		diagramtransitionmanipulator.cpp \
		transitionundocommand.cpp \
		stateaddplaceholder.cpp \
		stateundocommand.cpp \
		editorpanel.cpp \
		editorbase.cpp \
		editortransition.cpp \
		editorstate.cpp \
		editorevent.cpp \
		editorinput.cpp \
		editoroutput.cpp \
		outputlistmodel.cpp \
		availableactionsmodel.cpp \
		syntax/func.cpp \
		syntax/functions.cpp \
		syntax/keywords.cpp \
		syntax/scanner.cpp \
		syntax/scanner_atm.cpp \
		syntax/semantic.cpp \
		syntax/syntax.cpp \
		syntax/type.cpp \
		syntaxhighlighter.cpp \
		eventsinputsmodel.cpp \
		transitiontargetsmodel.cpp \
		linearsubsetmodel.cpp \
		textedit.cpp \
		application.cpp \
		editorroot.cpp \
		rootundocommand.cpp diagramscenefsm.cpp \
		manipfsm.cpp \
		qrc_ui.cpp \
		moc_mainwindow.cpp \
		moc_statemachine.cpp \
		moc_diagramview.cpp \
		moc_diagramscene.cpp \
		moc_stateaddplaceholder.cpp \
		moc_editorpanel.cpp \
		moc_editortransition.cpp \
		moc_editorstate.cpp \
		moc_editorevent.cpp \
		moc_editorinput.cpp \
		moc_editoroutput.cpp \
		moc_outputlistmodel.cpp \
		moc_availableactionsmodel.cpp \
		moc_eventsinputsmodel.cpp \
		moc_transitiontargetsmodel.cpp \
		moc_linearsubsetmodel.cpp \
		moc_textedit.cpp \
		moc_application.cpp \
		moc_editorroot.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qdombasic.o \
		statemachine.o \
		streamable.o \
		eiobase.o \
		event.o \
		input.o \
		output.o \
		root.o \
		state.o \
		transition.o \
		diagramview.o \
		diagramscene.o \
		diagramstateitem.o \
		gsavers.o \
		diagramtransitionitem.o \
		chaikinarrow.o \
		diagramtransitionmanipulator.o \
		transitionundocommand.o \
		stateaddplaceholder.o \
		stateundocommand.o \
		editorpanel.o \
		editorbase.o \
		editortransition.o \
		editorstate.o \
		editorevent.o \
		editorinput.o \
		editoroutput.o \
		outputlistmodel.o \
		availableactionsmodel.o \
		func.o \
		functions.o \
		keywords.o \
		scanner.o \
		scanner_atm.o \
		semantic.o \
		syntax.o \
		type.o \
		syntaxhighlighter.o \
		eventsinputsmodel.o \
		transitiontargetsmodel.o \
		linearsubsetmodel.o \
		textedit.o \
		application.o \
		editorroot.o \
		rootundocommand.o \
		diagramscenefsm.o \
		manipfsm.o \
		qrc_ui.o \
		moc_mainwindow.o \
		moc_statemachine.o \
		moc_diagramview.o \
		moc_diagramscene.o \
		moc_stateaddplaceholder.o \
		moc_editorpanel.o \
		moc_editortransition.o \
		moc_editorstate.o \
		moc_editorevent.o \
		moc_editorinput.o \
		moc_editoroutput.o \
		moc_outputlistmodel.o \
		moc_availableactionsmodel.o \
		moc_eventsinputsmodel.o \
		moc_transitiontargetsmodel.o \
		moc_linearsubsetmodel.o \
		moc_textedit.o \
		moc_application.o \
		moc_editorroot.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		fsme.pro mainwindow.h \
		qdombasic.h \
		qdomqvaluelist.h \
		statemachine.h \
		streamable.h \
		eiobase.h \
		nameexception.h \
		event.h \
		input.h \
		output.h \
		root.h \
		state.h \
		transition.h \
		diagramview.h \
		diagramscene.h \
		diagramstateitem.h \
		gsavers.h \
		diagramtransitionitem.h \
		chaikinarrow.h \
		scopeguard.h \
		diagramtransitionmanipulator.h \
		my_algo.h \
		transitionundocommand.h \
		stateaddplaceholder.h \
		stateundocommand.h \
		editorpanel.h \
		editorbase.h \
		editortransition.h \
		editorstate.h \
		editorevent.h \
		editorinput.h \
		editoroutput.h \
		outputlistmodel.h \
		availableactionsmodel.h \
		syntax/exception.h \
		syntax/lex.h \
		syntax/scanner.h \
		syntax/scanner_atm.h \
		syntax/semantic.h \
		syntax/syntax.h \
		syntax/type.h \
		syntaxhighlighter.h \
		eventsinputsmodel.h \
		transitiontargetsmodel.h \
		linearsubsetmodel.h \
		textedit.h \
		application.h \
		editorroot.h \
		rootundocommand.h \
		diagramscenefsm.h \
		manipfsm.h main.cpp \
		mainwindow.cpp \
		qdombasic.cpp \
		statemachine.cpp \
		streamable.cpp \
		eiobase.cpp \
		event.cpp \
		input.cpp \
		output.cpp \
		root.cpp \
		state.cpp \
		transition.cpp \
		diagramview.cpp \
		diagramscene.cpp \
		diagramstateitem.cpp \
		gsavers.cpp \
		diagramtransitionitem.cpp \
		chaikinarrow.cpp \
		diagramtransitionmanipulator.cpp \
		transitionundocommand.cpp \
		stateaddplaceholder.cpp \
		stateundocommand.cpp \
		editorpanel.cpp \
		editorbase.cpp \
		editortransition.cpp \
		editorstate.cpp \
		editorevent.cpp \
		editorinput.cpp \
		editoroutput.cpp \
		outputlistmodel.cpp \
		availableactionsmodel.cpp \
		syntax/func.cpp \
		syntax/functions.cpp \
		syntax/keywords.cpp \
		syntax/scanner.cpp \
		syntax/scanner_atm.cpp \
		syntax/semantic.cpp \
		syntax/syntax.cpp \
		syntax/type.cpp \
		syntaxhighlighter.cpp \
		eventsinputsmodel.cpp \
		transitiontargetsmodel.cpp \
		linearsubsetmodel.cpp \
		textedit.cpp \
		application.cpp \
		editorroot.cpp \
		rootundocommand.cpp
QMAKE_TARGET  = fsme
DESTDIR       = 
TARGET        = fsme


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_editorbase.h ui_editorstate.h ui_editortransition.h ui_editorroot.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fsme.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		fsme.pro \
		ui.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Xml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile fsme.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
fsme.pro:
ui.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Xml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile fsme.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents diagramscenefsm.fsm manipfsm.fsm $(DISTDIR)/
	$(COPY_FILE) --parents diagramscenefsm.fsm manipfsm.fsm $(DISTDIR)/
	$(COPY_FILE) --parents ui.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h qdombasic.h qdomqvaluelist.h statemachine.h streamable.h eiobase.h nameexception.h event.h input.h output.h root.h state.h transition.h diagramview.h diagramscene.h diagramstateitem.h gsavers.h diagramtransitionitem.h chaikinarrow.h scopeguard.h diagramtransitionmanipulator.h my_algo.h transitionundocommand.h stateaddplaceholder.h stateundocommand.h editorpanel.h editorbase.h editortransition.h editorstate.h editorevent.h editorinput.h editoroutput.h outputlistmodel.h availableactionsmodel.h syntax/exception.h syntax/lex.h syntax/scanner.h syntax/scanner_atm.h syntax/semantic.h syntax/syntax.h syntax/type.h syntaxhighlighter.h eventsinputsmodel.h transitiontargetsmodel.h linearsubsetmodel.h textedit.h application.h editorroot.h rootundocommand.h diagramscenefsm.h manipfsm.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp qdombasic.cpp statemachine.cpp streamable.cpp eiobase.cpp event.cpp input.cpp output.cpp root.cpp state.cpp transition.cpp diagramview.cpp diagramscene.cpp diagramstateitem.cpp gsavers.cpp diagramtransitionitem.cpp chaikinarrow.cpp diagramtransitionmanipulator.cpp transitionundocommand.cpp stateaddplaceholder.cpp stateundocommand.cpp editorpanel.cpp editorbase.cpp editortransition.cpp editorstate.cpp editorevent.cpp editorinput.cpp editoroutput.cpp outputlistmodel.cpp availableactionsmodel.cpp syntax/func.cpp syntax/functions.cpp syntax/keywords.cpp syntax/scanner.cpp syntax/scanner_atm.cpp syntax/semantic.cpp syntax/syntax.cpp syntax/type.cpp syntaxhighlighter.cpp eventsinputsmodel.cpp transitiontargetsmodel.cpp linearsubsetmodel.cpp textedit.cpp application.cpp editorroot.cpp rootundocommand.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui editorbase.ui editorstate.ui editortransition.ui editorroot.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_fsmheader_make_all: diagramscenefsm.h manipfsm.h
compiler_fsmheader_clean:
	-$(DEL_FILE) diagramscenefsm.h manipfsm.h
diagramscenefsm.h: diagramscenefsm.fsm
	/an/fsme-code/fsmtools/mkfsm.py -d -t /an/fsme-code/fsmtools/fsmheader.mako diagramscenefsm.fsm -o diagramscenefsm.h

manipfsm.h: manipfsm.fsm
	/an/fsme-code/fsmtools/mkfsm.py -d -t /an/fsme-code/fsmtools/fsmheader.mako manipfsm.fsm -o manipfsm.h

compiler_fsmbody_make_all: diagramscenefsm.cpp manipfsm.cpp
compiler_fsmbody_clean:
	-$(DEL_FILE) diagramscenefsm.cpp manipfsm.cpp
diagramscenefsm.cpp: diagramscenefsm.fsm \
		diagramscenefsm.h \
		diagramscenefsm.fsm
	/an/fsme-code/fsmtools/mkfsm.py -d -t /an/fsme-code/fsmtools/fsmbody.mako diagramscenefsm.fsm -o diagramscenefsm.cpp

manipfsm.cpp: manipfsm.fsm \
		manipfsm.h \
		manipfsm.fsm
	/an/fsme-code/fsmtools/mkfsm.py -d -t /an/fsme-code/fsmtools/fsmbody.mako manipfsm.fsm -o manipfsm.cpp

compiler_rcc_make_all: qrc_ui.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ui.cpp
qrc_ui.cpp: ui.qrc \
		/usr/lib/qt5/bin/rcc \
		images/minus@2x.png \
		images/delete@2x.png \
		images/undo.png \
		images/delete.png \
		images/scale-fit.png \
		images/event.png \
		images/scale-fit@2x.png \
		images/right@2x.png \
		images/add@2x.png \
		images/output@2x.png \
		images/up@2x.png \
		images/plus@2x.png \
		images/up.png \
		images/scale-original.png \
		images/add.png \
		images/input@2x.png \
		images/down@2x.png \
		images/down.png \
		images/back@2x.png \
		images/input.png \
		images/event@2x.png \
		images/redo@2x.png \
		images/plus.png \
		images/right.png \
		images/redo.png \
		images/minus.png \
		images/back.png \
		images/output.png \
		images/scale-original@2x.png \
		images/undo@2x.png
	/usr/lib/qt5/bin/rcc -name ui ui.qrc -o qrc_ui.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_statemachine.cpp moc_diagramview.cpp moc_diagramscene.cpp moc_stateaddplaceholder.cpp moc_editorpanel.cpp moc_editortransition.cpp moc_editorstate.cpp moc_editorevent.cpp moc_editorinput.cpp moc_editoroutput.cpp moc_outputlistmodel.cpp moc_availableactionsmodel.cpp moc_eventsinputsmodel.cpp moc_transitiontargetsmodel.cpp moc_linearsubsetmodel.cpp moc_textedit.cpp moc_application.cpp moc_editorroot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_statemachine.cpp moc_diagramview.cpp moc_diagramscene.cpp moc_stateaddplaceholder.cpp moc_editorpanel.cpp moc_editortransition.cpp moc_editorstate.cpp moc_editorevent.cpp moc_editorinput.cpp moc_editoroutput.cpp moc_outputlistmodel.cpp moc_availableactionsmodel.cpp moc_eventsinputsmodel.cpp moc_transitiontargetsmodel.cpp moc_linearsubsetmodel.cpp moc_textedit.cpp moc_application.cpp moc_editorroot.cpp
moc_mainwindow.cpp: mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_statemachine.cpp: nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		statemachine.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include statemachine.h -o moc_statemachine.cpp

moc_diagramview.cpp: diagramview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include diagramview.h -o moc_diagramview.cpp

moc_diagramscene.cpp: statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		diagramscenefsm.h \
		diagramscene.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include diagramscene.h -o moc_diagramscene.cpp

moc_stateaddplaceholder.cpp: stateaddplaceholder.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include stateaddplaceholder.h -o moc_stateaddplaceholder.cpp

moc_editorpanel.cpp: statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		editorpanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include editorpanel.h -o moc_editorpanel.cpp

moc_editortransition.cpp: editorbase.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		editortransition.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include editortransition.h -o moc_editortransition.cpp

moc_editorstate.cpp: editorbase.h \
		editorstate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include editorstate.h -o moc_editorstate.cpp

moc_editorevent.cpp: editorbase.h \
		editorevent.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include editorevent.h -o moc_editorevent.cpp

moc_editorinput.cpp: editorbase.h \
		editorinput.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include editorinput.h -o moc_editorinput.cpp

moc_editoroutput.cpp: editorbase.h \
		editoroutput.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include editoroutput.h -o moc_editoroutput.cpp

moc_outputlistmodel.cpp: outputlistmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include outputlistmodel.h -o moc_outputlistmodel.cpp

moc_availableactionsmodel.cpp: linearsubsetmodel.h \
		availableactionsmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include availableactionsmodel.h -o moc_availableactionsmodel.cpp

moc_eventsinputsmodel.cpp: eventsinputsmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include eventsinputsmodel.h -o moc_eventsinputsmodel.cpp

moc_transitiontargetsmodel.cpp: linearsubsetmodel.h \
		transitiontargetsmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include transitiontargetsmodel.h -o moc_transitiontargetsmodel.cpp

moc_linearsubsetmodel.cpp: linearsubsetmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include linearsubsetmodel.h -o moc_linearsubsetmodel.cpp

moc_textedit.cpp: textedit.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include textedit.h -o moc_textedit.cpp

moc_application.cpp: application.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include application.h -o moc_application.cpp

moc_editorroot.cpp: editorbase.h \
		editorroot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /an/fsme-code/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/an/fsme-code -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include editorroot.h -o moc_editorroot.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_editorbase.h ui_editorstate.h ui_editortransition.h ui_editorroot.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_editorbase.h ui_editorstate.h ui_editortransition.h ui_editorroot.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		editorpanel.h \
		editorevent.h \
		editorinput.h \
		editoroutput.h \
		editorstate.h \
		editortransition.h \
		editorroot.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		editorbase.h \
		editorbase.h \
		editorbase.h \
		editorbase.h \
		editorbase.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		editorbase.h
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_editorbase.h: editorbase.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic editorbase.ui -o ui_editorbase.h

ui_editorstate.h: editorstate.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic editorstate.ui -o ui_editorstate.h

ui_editortransition.h: editortransition.ui \
		/usr/lib/qt5/bin/uic \
		textedit.h
	/usr/lib/qt5/bin/uic editortransition.ui -o ui_editortransition.h

ui_editorroot.h: editorroot.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic editorroot.ui -o ui_editorroot.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_fsmheader_clean compiler_fsmbody_clean compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		application.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		editorevent.h \
		editorbase.h \
		editorinput.h \
		editoroutput.h \
		editorpanel.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		editorroot.h \
		editorstate.h \
		editortransition.h \
		diagramscene.h \
		diagramscenefsm.h \
		scopeguard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qdombasic.o: qdombasic.cpp qdombasic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdombasic.o qdombasic.cpp

statemachine.o: statemachine.cpp statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		gsavers.h \
		streamable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statemachine.o statemachine.cpp

streamable.o: streamable.cpp streamable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o streamable.o streamable.cpp

eiobase.o: eiobase.cpp statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eiobase.o eiobase.cpp

event.o: event.cpp event.h \
		eiobase.h \
		nameexception.h \
		statemachine.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o event.o event.cpp

input.o: input.cpp input.h \
		eiobase.h \
		nameexception.h \
		statemachine.h \
		event.h \
		root.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o input.o input.cpp

output.o: output.cpp output.h \
		eiobase.h \
		nameexception.h \
		statemachine.h \
		event.h \
		root.h \
		input.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		transitionundocommand.h \
		stateundocommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o output.o output.cpp

root.o: root.cpp statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		rootundocommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o root.o root.cpp

state.o: state.cpp statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		stateundocommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o state.o state.cpp

transition.o: transition.cpp statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		transitionundocommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transition.o transition.cpp

diagramview.o: diagramview.cpp diagramview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramview.o diagramview.cpp

diagramscene.o: diagramscene.cpp scopeguard.h \
		diagramscene.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		diagramscenefsm.h \
		diagramstateitem.h \
		stateaddplaceholder.h \
		stateundocommand.h \
		diagramtransitionitem.h \
		chaikinarrow.h \
		diagramtransitionmanipulator.h \
		manipfsm.h \
		transitionundocommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramscene.o diagramscene.cpp

diagramstateitem.o: diagramstateitem.cpp diagramstateitem.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		diagramscene.h \
		diagramscenefsm.h \
		diagramtransitionitem.h \
		chaikinarrow.h \
		scopeguard.h \
		my_algo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramstateitem.o diagramstateitem.cpp

gsavers.o: gsavers.cpp qdombasic.h \
		qdomqvaluelist.h \
		gsavers.h \
		streamable.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		diagramview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gsavers.o gsavers.cpp

diagramtransitionitem.o: diagramtransitionitem.cpp diagramtransitionitem.h \
		chaikinarrow.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		diagramscene.h \
		diagramscenefsm.h \
		diagramstateitem.h \
		my_algo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramtransitionitem.o diagramtransitionitem.cpp

chaikinarrow.o: chaikinarrow.cpp chaikinarrow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chaikinarrow.o chaikinarrow.cpp

diagramtransitionmanipulator.o: diagramtransitionmanipulator.cpp diagramtransitionmanipulator.h \
		manipfsm.h \
		diagramtransitionitem.h \
		chaikinarrow.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		transitionundocommand.h \
		diagramscene.h \
		diagramscenefsm.h \
		my_algo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramtransitionmanipulator.o diagramtransitionmanipulator.cpp

transitionundocommand.o: transitionundocommand.cpp output.h \
		eiobase.h \
		nameexception.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		statemachine.h \
		event.h \
		root.h \
		input.h \
		my_algo.h \
		transitionundocommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transitionundocommand.o transitionundocommand.cpp

stateaddplaceholder.o: stateaddplaceholder.cpp stateaddplaceholder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stateaddplaceholder.o stateaddplaceholder.cpp

stateundocommand.o: stateundocommand.cpp stateundocommand.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		transitionundocommand.h \
		rootundocommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stateundocommand.o stateundocommand.cpp

editorpanel.o: editorpanel.cpp statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		editorpanel.h \
		editorbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editorpanel.o editorpanel.cpp

editorbase.o: editorbase.cpp editorbase.h \
		eiobase.h \
		nameexception.h \
		ui_editorbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editorbase.o editorbase.cpp

editortransition.o: editortransition.cpp editortransition.h \
		editorbase.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		ui_editortransition.h \
		textedit.h \
		scopeguard.h \
		availableactionsmodel.h \
		linearsubsetmodel.h \
		transitionundocommand.h \
		stateundocommand.h \
		syntaxhighlighter.h \
		eventsinputsmodel.h \
		transitiontargetsmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editortransition.o editortransition.cpp

editorstate.o: editorstate.cpp editorstate.h \
		editorbase.h \
		scopeguard.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		stateundocommand.h \
		ui_editorstate.h \
		availableactionsmodel.h \
		linearsubsetmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editorstate.o editorstate.cpp

editorevent.o: editorevent.cpp editorevent.h \
		editorbase.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		ui_editorbase.h \
		scopeguard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editorevent.o editorevent.cpp

editorinput.o: editorinput.cpp editorinput.h \
		editorbase.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		ui_editorbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editorinput.o editorinput.cpp

editoroutput.o: editoroutput.cpp editoroutput.h \
		editorbase.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		ui_editorbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editoroutput.o editoroutput.cpp

outputlistmodel.o: outputlistmodel.cpp outputlistmodel.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		transition.h \
		scopeguard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o outputlistmodel.o outputlistmodel.cpp

availableactionsmodel.o: availableactionsmodel.cpp availableactionsmodel.h \
		linearsubsetmodel.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o availableactionsmodel.o availableactionsmodel.cpp

func.o: syntax/func.cpp syntax/semantic.h \
		syntax/type.h \
		syntax/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o func.o syntax/func.cpp

functions.o: syntax/functions.cpp syntax/semantic.h \
		syntax/type.h \
		syntax/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functions.o syntax/functions.cpp

keywords.o: syntax/keywords.cpp syntax/scanner.h \
		syntax/scanner_atm.h \
		syntax/lex.h \
		syntax/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keywords.o syntax/keywords.cpp

scanner.o: syntax/scanner.cpp syntax/scanner.h \
		syntax/scanner_atm.h \
		syntax/lex.h \
		syntax/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scanner.o syntax/scanner.cpp

scanner_atm.o: syntax/scanner_atm.cpp syntax/scanner_atm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scanner_atm.o syntax/scanner_atm.cpp

semantic.o: syntax/semantic.cpp syntax/semantic.h \
		syntax/type.h \
		syntax/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o semantic.o syntax/semantic.cpp

syntax.o: syntax/syntax.cpp syntax/syntax.h \
		syntax/scanner.h \
		syntax/scanner_atm.h \
		syntax/lex.h \
		syntax/exception.h \
		syntax/semantic.h \
		syntax/type.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o syntax.o syntax/syntax.cpp

type.o: syntax/type.cpp syntax/type.h \
		syntax/semantic.h \
		syntax/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o type.o syntax/type.cpp

syntaxhighlighter.o: syntaxhighlighter.cpp syntaxhighlighter.h \
		syntax/syntax.h \
		syntax/scanner.h \
		syntax/scanner_atm.h \
		syntax/lex.h \
		syntax/exception.h \
		syntax/semantic.h \
		syntax/type.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o syntaxhighlighter.o syntaxhighlighter.cpp

eventsinputsmodel.o: eventsinputsmodel.cpp eventsinputsmodel.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventsinputsmodel.o eventsinputsmodel.cpp

transitiontargetsmodel.o: transitiontargetsmodel.cpp statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transitiontargetsmodel.o transitiontargetsmodel.cpp

linearsubsetmodel.o: linearsubsetmodel.cpp linearsubsetmodel.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		scopeguard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o linearsubsetmodel.o linearsubsetmodel.cpp

textedit.o: textedit.cpp textedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textedit.o textedit.cpp

application.o: application.cpp application.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o application.o application.cpp

editorroot.o: editorroot.cpp editorroot.h \
		editorbase.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h \
		ui_editorroot.h \
		scopeguard.h \
		rootundocommand.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editorroot.o editorroot.cpp

rootundocommand.o: rootundocommand.cpp rootundocommand.h \
		statemachine.h \
		nameexception.h \
		event.h \
		eiobase.h \
		root.h \
		input.h \
		output.h \
		state.h \
		outputlistmodel.h \
		transition.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rootundocommand.o rootundocommand.cpp

diagramscenefsm.o: diagramscenefsm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diagramscenefsm.o diagramscenefsm.cpp

manipfsm.o: manipfsm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o manipfsm.o manipfsm.cpp

qrc_ui.o: qrc_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ui.o qrc_ui.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_statemachine.o: moc_statemachine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_statemachine.o moc_statemachine.cpp

moc_diagramview.o: moc_diagramview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diagramview.o moc_diagramview.cpp

moc_diagramscene.o: moc_diagramscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diagramscene.o moc_diagramscene.cpp

moc_stateaddplaceholder.o: moc_stateaddplaceholder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stateaddplaceholder.o moc_stateaddplaceholder.cpp

moc_editorpanel.o: moc_editorpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editorpanel.o moc_editorpanel.cpp

moc_editortransition.o: moc_editortransition.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editortransition.o moc_editortransition.cpp

moc_editorstate.o: moc_editorstate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editorstate.o moc_editorstate.cpp

moc_editorevent.o: moc_editorevent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editorevent.o moc_editorevent.cpp

moc_editorinput.o: moc_editorinput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editorinput.o moc_editorinput.cpp

moc_editoroutput.o: moc_editoroutput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editoroutput.o moc_editoroutput.cpp

moc_outputlistmodel.o: moc_outputlistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_outputlistmodel.o moc_outputlistmodel.cpp

moc_availableactionsmodel.o: moc_availableactionsmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_availableactionsmodel.o moc_availableactionsmodel.cpp

moc_eventsinputsmodel.o: moc_eventsinputsmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventsinputsmodel.o moc_eventsinputsmodel.cpp

moc_transitiontargetsmodel.o: moc_transitiontargetsmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_transitiontargetsmodel.o moc_transitiontargetsmodel.cpp

moc_linearsubsetmodel.o: moc_linearsubsetmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_linearsubsetmodel.o moc_linearsubsetmodel.cpp

moc_textedit.o: moc_textedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textedit.o moc_textedit.cpp

moc_application.o: moc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_application.o moc_application.cpp

moc_editorroot.o: moc_editorroot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editorroot.o moc_editorroot.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

